Part 2
e-smirnov735/test-guru pull request #1
Opened 2023-03-02 11:37 UTC by e-smirnov735

2023-03-02 13:57 UTC, VidgarVii requested changes

2023-03-02 13:57 UTC, VidgarVii commented on README.md
> +* Question - Конкретный вопрос. ТАк же хранит правильный ответ, категорию и возможно сложность.
как-то мало получилось сущностей )))

список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2023-03-02 13:57 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}')]
что делает этот конфиг?)

2023-03-02 13:57 UTC, VidgarVii commented on config/locales/ru.yml
> +  hello: "Привет мир!"
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-03-02 13:57 UTC, VidgarVii commented on public/about.html
> +      <a href="https://www.thinknetica.com">www.thinknetica.com</a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2023-03-02 15:40 UTC, e-smirnov735 commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}')]
да тут скопировал не подумав. Строка нужна, только если мы меняем местонахождение папки locales.

2023-03-02 15:41 UTC, e-smirnov735 commented on public/about.html
> +      <a href="https://www.thinknetica.com">www.thinknetica.com</a>
принято

2023-03-02 15:42 UTC, e-smirnov735 commented on config/locales/ru.yml
> +  hello: "Привет мир!"
принято

2023-03-02 15:46 UTC, e-smirnov735 commented on README.md
> +* Question - Конкретный вопрос. ТАк же хранит правильный ответ, категорию и возможно сложность.
Меню, База данных... больше пока в голову ничего не приходит. 
Или тут имееется ввиду сущности, как бы Модели (Models) или и остальные Контроллеры, Вью и тд?

2023-03-03 08:19 UTC, VidgarVii commented on README.md
> +* Answer - ответ.
Еще нужен Результат куда будем записывать пройденные тесты юзера

2023-03-03 13:37 UTC, merged