feat: routes and controller for questions
e-smirnov735/test-guru pull request #6
Opened 2023-03-22 19:48 UTC by e-smirnov735

2023-03-23 05:05 UTC, VidgarVii requested changes

2023-03-23 05:05 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  rescue => e
1 Нельзя обрабатывать сразу все ошибки. Мб ты где-то опечатался, а сервер вернёт 404, что не верно.
2 https://apidock.com/rails/ActiveSupport/Rescuable/ClassMethods/rescue_from

2023-03-23 05:05 UTC, VidgarVii commented on config/routes.rb
> +  get '/questions/:id/delete', to: 'questions#delete'
**Создайте ресурс Вопросов, вложенный в ресурс Тестов**

Для вложенных ресурсов есть механизм написание роутов. Лишнего объявлять ни чего не нужно
http://rusrails.ru/routing#vlozhennye-resursy

2023-03-23 05:05 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +    <input type="text" name="question[test_id]" id="test-id">
при правильном роутинге параметр test_id будет приходить через путь запроса

2023-03-23 05:05 UTC, VidgarVii commented on app/views/questions/delete.html.erb
> +<h1>Удаление вопроса</h1>
согласно REST за удаление ресурса отвечает метод DELETE. И после удаления юзера отправляют на какую-нибудь страницу.
Этот вью не нужен

2023-03-23 05:05 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    Question.create!(question_params)
нужно проверять сохранен ли объект.
Если сохранен, то редиректим нужную страницу
если нет, то рендерим форму заново. 
В объекте вопроса будут сохранены ошибки валидации, которые в будущем покажем пользователю

2023-03-23 05:05 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  def delete; end
Ни в REST не в CRUD нет такого экшена.
экшен для удаление вопросов уже есть. это destroy. Достаточно будет вывести кнопку около вопроса, которая будет удалять вопрос. И то это будем делать на следующем задании. Сейчас главное научиться пользоваться контроллерами.

2023-03-24 06:41 UTC, VidgarVii requested changes

2023-03-24 06:41 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлемо) опцию `shallow: true`
Это уменьшит кол-во запросов в контроллере. Упростит код и укоротит http запрос
[вот](http://rusrails.ru/rails-routing#melkoe-vlozhenie) документация на русском

2023-03-24 06:41 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="<%= test_questions_path %>" method="post">
ссылка не корректная. Для какого теста будет создан вопрос? Ид теста должен передаваться через путь запроса

2023-03-24 06:41 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
здесь и в `question_params` какая-то путанница...
в `question_params` не должен входить `test_id`, этот аттрибут идет в параметрах, но не под ключом `:question`
метод же `question_params` должен возвращать только аттрибуты идущие в параметрах под ключом `:question`
а остальные параметры вопроса как раз должны идти под ключом `:question` (в нашем случае `body`)
поэтому нужно `@test` для этого экшена найти так же, как для индекса и здесь воспользоваться ассоциацией:
```ruby
@test.questions.create(...)
```

2023-03-24 06:41 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_questions_path
лучше всегда писать путь согласно конвенции, т.е. с явной передачей аргумента в хелпер:
```ruby
test_questions_path(@test)
```

2023-03-24 06:41 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_questions_path
обычно после создания ресурса, юзера отправляют на страницу этого ресурса

2023-03-24 06:41 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to new_test_question_path
если ресурс не создался из-за ошибок валидаций, то перезагружать всю страницу не надо. Делают `render :show` Это позволит нам показать ошибки валидации объекта @question

2023-03-24 13:57 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      render :show, status: :bad_request
статус 400 тут не верен, так как сервер корректно отрабатывает полученные данные

2023-03-24 14:02 UTC, e-smirnov735 commented on app/controllers/questions_controller.rb
> +      render :show, status: :bad_request
убрал

2023-03-24 14:03 UTC, merged